Repository thoth-station/package-update-job, pull requests merged in 2020-03, with the labels that each got.

#19 Convert app to faust app
  Pipfile
  Pipfile.lock
  app.sh
  messages/hash_mismatch.py
  messages/message_base.py
  package_update.py
Labels: approved, size/L

#28 Patch set comprehension
  package_update.py
Labels: approved

#30 Automatic update of dependency thoth-common from 0.10.9 to 0.10.11
  Pipfile.lock
Labels: bot, size/M

#31 Add empty env template
  .env.template
Labels: approved, size/S

#33 Adjust name
  .github/CODEOWNERS
  messages/__init__.py
Labels: approved, size/XS

#35 Automatic update of dependency thoth-storages from 0.22.3 to 0.22.5
  Pipfile.lock
Labels: bot, size/M

#32 Automatic update of dependency thoth-common from 0.10.11 to 0.10.12
  Pipfile.lock
Labels: bot, size/XS

#36 Automatic update of dependency thoth-common from 0.10.12 to 0.12.3
  Pipfile.lock
Labels: bot, size/M

#37 Automatic update of dependency thoth-common from 0.12.3 to 0.12.4
  Pipfile.lock
Labels: bot, size/S

#38 Automatic update of dependency thoth-storages from 0.22.5 to 0.22.6
  Pipfile.lock
Labels: bot, size/S

#8 std prk cfg fls
  .coafile
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/new_deployment.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/user_story.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .pre-commit-config.yaml
  .thoth.yaml
  Pipfile
  Pipfile.lock
  README.md
  app.py
  messages/message_base.py
Labels: approved, size/XL
