Repository thoth-station/package-update-job, pull requests merged in 2020-09, with the labels that each got.

#124 update messaging and add component_name and version
  Pipfile.lock
  producer.py
Labels: approved, size/L

#127 Release of version 0.8.1
  CHANGELOG.md
  package_update/__init__.py
Labels: approved, bot, size/XS

#128 Automatic update of dependency thoth-storages from 0.25.5 to 0.25.6
  Pipfile.lock
Labels: approved, bot, size/L

#130 remove consumer logic (moved to investigator)
  app.sh
  consumer.py
  package_update/metrics.py
  package_update/process_message.py
  producer.py
Labels: approved, size/L

#131 Automatic update of dependency thoth-storages from 0.25.6 to 0.25.11
  Pipfile.lock
Labels: approved, bot, size/L

#132 Automatic update of dependency thoth-sourcemanagement from 0.3.0 to 0.3.2
  Pipfile.lock
Labels: approved, bot, size/L

#133 Automatic update of dependency thoth-messaging from 0.7.0 to 0.7.6
  Pipfile.lock
Labels: approved, bot, size/L

#134 Automatic update of dependency thoth-messaging from 0.7.0 to 0.7.6
  Pipfile.lock
Labels: approved, bot, size/S

#135 Automatic update of dependency pytest from 6.0.1 to 6.0.2
  Pipfile.lock
Labels: approved, bot, size/L

#141 Automatic update of dependency thoth-python from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: approved, bot, size/L

#142 Release of version 0.8.2
  CHANGELOG.md
  package_update/__init__.py
Labels: approved, bot, size/S

#153 Automatic update of dependency thoth-messaging from 0.7.6 to 0.7.7
  Pipfile.lock
Labels: approved, bot, size/M

#154 Automatic update of dependency pytest from 6.0.2 to 6.1.0
  Pipfile.lock
Labels: approved, bot, size/M

#155 Automatic update of dependency thoth-storages from 0.25.11 to 0.25.12
  Pipfile.lock
Labels: approved, bot, size/S

#156 Automatic update of dependency thoth-messaging from 0.7.7 to 0.7.8
  Pipfile.lock
Labels: approved, bot, size/XS

#157 Automatic update of dependency thoth-storages from 0.25.12 to 0.25.13
  Pipfile.lock
Labels: approved, bot, size/XS
