Repository thoth-station/package-update-job, pull requests merged in 2020-02, with the labels that each got.

#6 Add openshift namespace for build trigger
  .zuul.yaml
Labels: approved, size/XS

#2 Do not initialize/update database schema
  app.py
Labels: approved, size/XS

#7 Remove kafka
  Pipfile.lock
  messages/hash_mismatch.py
  messages/message_base.py
  messages/missing_package.py
  messages/missing_version.py
Labels: approved, size/M

#5 update templates for test-core
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
Labels: approved, size/S

#11 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#15 update topic names to thoth.package-update.X
  messages/hash_mismatch.py
  messages/message_base.py
  messages/missing_package.py
  messages/missing_version.py
Labels: approved, size/S

#16 remove limits on number of python-packages
  app.py
Labels: approved, size/XS

#18 Use unique flag as to not check repeat packages
  app.py
Labels: approved, size/XS

#1 Update metrics
  Pipfile
  Pipfile.lock
  app.py
Labels: approved, size/M

#25 Use tuple as an item in hash
  app.py
Labels: approved, size/XS

#24 Automatic update of dependency thoth-storages from 0.21.11 to 0.22.3
  Pipfile.lock
Labels: bot, size/L

#22 Move app.py to package_update.py
  app.sh
  openshift/cronJob-template.yaml
  package_update.py
Labels: approved, size/S
