Repository thoth-station/package-update-job, pull requests merged in 2020-05, with the labels that each got.

#59 Automatic update of dependency pylint from 2.5.0 to 2.5.1
  Pipfile.lock
Labels: bot, size/M

#60 Automatic update of dependency pylint from 2.5.1 to 2.5.2
  Pipfile.lock
Labels: bot, size/XS

#61 Automatic update of dependency thoth-messaging from 0.3.4 to 0.3.5
  Pipfile.lock
Labels: bot, size/S

#62 Automatic update of dependency pytest from 5.4.1 to 5.4.2
  Pipfile.lock
Labels: bot, size/M

#58 move to sub directory and add init file
  app.sh
  package_update/__init__.py
  package_update/package_update.py
  package_update/process_message.py
  package_update/update_consumer.py
Labels: approved, size/M

#63 Automatic update of dependency thoth-messaging from 0.3.5 to 0.3.6
  Pipfile.lock
Labels: bot, size/S

#64 Automatic update of dependency pre-commit from 2.3.0 to 2.4.0
  Pipfile.lock
Labels: bot, size/S

#65 Automatic update of dependency thoth-sourcemanagement from 0.2.7 to 0.2.9
  Pipfile.lock
Labels: bot, size/S

#66 Automatic update of dependency thoth-storages from 0.22.9 to 0.22.10
  Pipfile.lock
Labels: bot, size/S

#67 Automatic update of dependency thoth-storages from 0.22.10 to 0.22.11
  Pipfile.lock
Labels: bot, size/L

#68 Automatic update of dependency thoth-storages from 0.22.11 to 0.22.12
  Pipfile.lock
Labels: bot, size/M
