Repository thoth-station/package-update-job, pull requests merged in 2020-04, with the labels that each got.

#26 Consumer
  .env.template
  Pipfile
  Pipfile.lock
  app.sh
  messages/__init__.py
  messages/hash_mismatch.py
  messages/missing_package.py
  messages/missing_version.py
  openshift/buildConfig-template.yaml
  openshift/consumer-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
  package_update.py
  process_message.py
  update_consumer.py
Labels: approved, size/XXL

#40 Correct key for ConfigMap
  openshift/consumer-template.yaml
Labels: approved, size/XS

#41 remove app.py
  app.py
Labels: approved, size/M

#43 messages only present in messaging module
  messages/message_base.py
Labels: approved, size/M

#46 Add Route and correct port
  openshift/consumer-template.yaml
Labels: approved, size/S

#47 Correct errors
  openshift/consumer-template.yaml
Labels: approved, size/XS

#51 Automatic update of dependency thoth-python from 0.9.1 to 0.9.2
  Pipfile.lock
Labels: bot, size/L

#52 Automatic update of dependency pre-commit from 2.2.0 to 2.3.0
  Pipfile.lock
Labels: bot, size/M

#53 remove service account
  openshift/consumer-template.yaml
Labels: approved, size/S

#54 Automatic update of dependency thoth-storages from 0.22.7 to 0.22.8
  Pipfile.lock
Labels: bot, size/L

#55 Automatic update of dependency pylint from 2.4.4 to 2.5.0
  Pipfile.lock
Labels: bot, size/L

#56 add FAUST_DEBUG env option
  app.sh
Labels: approved, size/S

#57 Automatic update of dependency thoth-storages from 0.22.8 to 0.22.9
  Pipfile.lock
Labels: bot
