Repository thoth-station/package-update-job, pull requests merged in 2020-07, with the labels that each got.

#86 Automatic update of dependency thoth-storages from 0.24.0 to 0.24.2
  Pipfile.lock
Labels: approved, bot, size/M

#87 Automatic update of dependency pre-commit from 2.5.1 to 2.6.0
  Pipfile.lock
Labels: approved, bot, size/M

#90 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#93 Release of version 0.7.0
  CHANGELOG.md
  package_update/__init__.py
Labels: approved, bot, size/L

#94 enable pre-commit support for the application
  .zuul.yaml
  package_update/package_update.py
  package_update/process_message.py
Labels: approved, size/M

#95 Remove old bits
  package_update/process_message.py
Labels: approved, size/S

#96 Remove templates handled by thoth-application
  openshift/buildConfig-template.yaml
  openshift/consumer-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/XL

#97 use asyncio for sending messages
  package_update/package_update.py
Labels: approved, size/L

#98 Automatic update of dependency thoth-storages from 0.24.2 to 0.24.3
  Pipfile.lock
Labels: approved, bot, size/L

#99 Automatic update of dependency thoth-messaging from 0.3.6 to 0.3.7
  Pipfile.lock
Labels: approved, bot, size/L

#100 Automatic update of dependency pytest from 5.4.3 to 6.0.0rc1
  Pipfile.lock
Labels: approved, bot, size/L

#104 Remove unused env variable
  .env.template
Labels: approved, size/XS

#105 Remove latest versions limitation
  .thoth.yaml
Labels: approved, size/XS

#106 Automatic update of dependency thoth-storages from 0.24.3 to 0.24.4
  Pipfile.lock
Labels: approved, bot

#108 Automatic update of dependency thoth-messaging from 0.3.7 to 0.5.0
  Pipfile.lock
Labels: approved, bot, size/M

#110 Automatic update of dependency thoth-storages from 0.24.4 to 0.24.5
  Pipfile.lock
Labels: approved, bot, size/S

#109 Feature/persistent metrics
  Pipfile.lock
  app.sh
  consumer.py
  package_update/__init__.py
  package_update/metrics.py
  package_update/process_message.py
  producer.py
Labels: approved, size/L

#111 Automatic update of dependency pytest from 5.4.3 to 6.0.0rc1
  Pipfile.lock
Labels: approved, bot, size/L
