Repository thoth-station/package-update-job, pull requests merged in 2020-10, with the labels that each got.

#151 exception won't cause runtime failure
  producer.py
Labels: approved, size/S

#158 Automatic update of dependency thoth-storages from 0.25.13 to 0.25.14
  Pipfile.lock
Labels: approved, bot, size/M

#159 Automatic update of dependency thoth-messaging from 0.7.8 to 0.7.10
  Pipfile.lock
Labels: approved, bot, size/M

#163 Release of version 0.8.3
  CHANGELOG.md
  package_update/__init__.py
Labels: approved, bot, size/S

#164 lock down thoth-messaging
  Pipfile
  Pipfile.lock
Labels: approved, size/XL
