Repository thoth-station/package-update-job, pull requests merged in 2020-11, with the labels that each got.

#167 Automatic update of dependency thoth-storages from 0.25.15 to 0.26.0
  Pipfile.lock
Labels: approved, bot, size/XL

#168 Automatic update of dependency thoth-sourcemanagement from 0.3.2 to 0.3.3
  Pipfile.lock
Labels: approved, bot, size/XL

#170 Automatic update of dependency pre-commit from 2.7.1 to 2.8.2
  Pipfile.lock
Labels: approved, bot, size/XL

#172 Automatic update of dependency pytest from 6.1.1 to 6.1.2
  Pipfile.lock
Labels: approved, bot, size/XL

#175 Release of version 0.8.4
  CHANGELOG.md
  package_update/__init__.py
Labels: approved, bot, size/S

#176 port to python 38
  .aicoe-ci.yaml
  Pipfile
  Pipfile.lock
Labels: approved, size/XL

#177 update .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#179 set base to v0.20.1
  .aicoe-ci.yaml
Labels: approved, size/XS
