Repository thoth-station/package-update-job, pull requests merged in 2021-02, with the labels that each got.

#192 fix the typing extension installation issue
  .github/ISSUE_TEMPLATE/kebechet_info.md
  .github/ISSUE_TEMPLATE/kebechet_update.md
  Pipfile.lock
Labels: approved, size/S

#198 Removed unused package imports
  producer.py
Labels: approved, size/M

#201 use py38 image
  .aicoe-ci.yaml
Labels: approved, size/XS
